### ISSUE TITLE
updating anime list is not working fsr

### ISSUE THREAD

**Issue by YipWig** [varoOP/shinkro#39]
Hey , i've been looking for a way to auto update my anime list when i watch anime on plex so i found this app , i tried to set it up and managed to connect my account with an application id and secret it like so :

Myanime authentication success ![image](https://github.com/varoOP/shinkro/assets/82726308/baf216a8-b2e7-4ed2-833b-81989824cb14)

Then i added a Tattuli notification agent like so : 
![image](https://github.com/varoOP/shinkro/assets/82726308/4faaa901-628f-49ea-99cc-35367b47a824)
![image](https://github.com/varoOP/shinkro/assets/82726308/bc914f6e-da12-47a1-9944-f56e683d31e0)
![image](https://github.com/varoOP/shinkro/assets/82726308/e92a21ca-074e-4bf1-ae2a-9c15500c3a66)
![image](https://github.com/varoOP/shinkro/assets/82726308/c4b40f97-ef7f-4d78-8b8f-7878ef66583b)

and then i tried to watch an episode on Plex ( Tsuredure Children ep 5 ) but it did not change anything on myanimelist , have i missed something ?

**Comment by YipWig** [comment]
oh btw i added the api key in the webhook url but not working either

**Comment by varoOP** [comment]
Hey, the webhook URL needs to hit the /api/plex end point. Try changing it to the following:
http://192.168.1.3:7011/api/plex?apiKey={copy_paste_the_api_key_here}

Also, just copy-paste the json data from the docs, no need to edit it. If you want to hardcode your Plex username still, then remove the curly brackets around it.

**Comment by varoOP** [comment]
I am closing the issue, assuming it's resolved. Feel free to reach out on discord if it isn't.
