### ISSUE TITLE
Started getting error "Unauthorized" about 2 days ago

### ISSUE THREAD

**Issue by PedroBuffon** [varoOP/shinkro#40]
Hi, i started getting the following error message when trying to update MAL episode.
The following error message is from portainer docker log:
`failed to send update to myanimelist error="invalid character '<' looking for beginning of value, response status: 401, response body: <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>" action=animeUpdate module=server stack=[{"func":"(*PlexClient).GetShowID","line":"55","source":"client.go"},{"func":"GetShowID","line":"156","source":"media.go"},{"func":"NewMedia","line":"55","source":"media.go"},{"func":"(*AnimeUpdate).parseMedia","line":"338","source":"update.go"},{"func":"(*AnimeUpdate).SendUpdate","line":"70","source":"update.go"},{"func":"NewRouter.func2.1.1.plexHandler.func2","line":"38","source":"handlers.go"},{"func":"HandlerFunc.ServeHTTP","line":"2136","source":"server.go"},{"func":"(*Mux).routeHTTP","line":"436","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2136","source":"server.go"},{"func":"NewRouter.func2.1.1.checkPlexPayload.func1.1","line":"163","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2136","source":"server.go"},{"func":"parsePlexPayload.func1","line":"100","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2136","source":"server.go"},{"func":"AllowContentType.func1.1","line":"41","source":"content_type.go"},{"func":"HandlerFunc.ServeHTTP","line":"2136","source":"server.go"},{"func":"onlyAllowPost.func1","line":"80","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2136","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"70","source":"mux.go"},{"func":"(*Mux).Mount.func1","line":"311","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2136","source":"server.go"},{"func":"(*Mux).routeHTTP","line":"436","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2136","source":"server.go"},{"func":"NewRouter.func2.1.auth.func2.1","line":"30","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2136","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"70","source":"mux.go"},{"func":"(*Mux).Mount.func1","line":"311","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2136","source":"server.go"},{"func":"(*Mux).routeHTTP","line":"436","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2136","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"70","source":"mux.go"},{"func":"(*Mux).Mount.func1","line":"311","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2136","source":"server.go"}]`

**Comment by varoOP** [comment]
Hi, shinkro is having trouble connecting to your Plex Media Server instance. Please double check that both Plex URL and Plex Token settings in the shinkro config are still valid. If no changes have occurred to the token and URL of your Plex instance, then this could be some sort of API change with Plex. 

Please share the version of Plex Media Server that you are using and I'll be happy to look into this further. :D

**Comment by PedroBuffon** [comment]
My Plex version is 1.84.1.4069-ff740b6d, running on docker, i tried setting up Shinkro again but the same problem appears.

**Comment by PedroBuffon** [comment]
I've redone my config file and recreated my MAL api and i got it working again, idk exactly what went wrong before hehehe. Now everything works.

**Comment by varoOP** [comment]
Glad it's working again! Feel free to reopen the issue if it returns. Would appreciate having the TRACE logs then, could be able to pin out the cause :)
