### ISSUE TITLE
error: failed switching to "shinkrousr": unable to find user shinkrousr: no matching entries in passwd file

### ISSUE THREAD

**Issue by Fribb** [varoOP/shinkro#43]
System information:
* Unraid: 6.12.6
* Docker: 20.10.24, build 297e128

When I want to create a Container of this project on my Unraid Server I get the following log output:

> addgroup: gid '100' in use
> adduser: unknown group shinkrogrp
> error: failed switching to "shinkrousr": unable to find user shinkrousr: no matching entries in passwd file

This is the docker run command that is created through the Unraid Template (basically a user-friendly way to create your own Docker containers without having to do that through the console or compose).

```
docker run
  -d
  --name='Shinkro'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Fribb-Tower"
  -e HOST_CONTAINERNAME="Shinkro"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'SHINKRO_USERNAME'='shinkro'
  -e 'SHINKRO_PASSWORD'='shinkro'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:7011]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/varoOP/shinkro/develop/.github/images/logo.png'
  -v '/mnt/user/appdata/shinkro':'/config':'rw' 'ghcr.io/varoop/shinkro:latest'
```

Most of the parameters are probably not relevant to this problem, I just wanted to mention the whole command.

Those PUID and PGID are standardized for Unraid systems.

**Comment by varoOP** [comment]
Hi Fribb, 

I didn't consider the user/group with passed PID & GID already existing in the container. I have updated the entrypoint script.

Please test with the latest docker image and let me know if that fixes this issue.

Thanks for MyAnimeList.bundle!

**Comment by Fribb** [comment]
Thank you for the quick fix, it is working now.
