### ISSUE TITLE
unauthorized plex user

### ISSUE THREAD

**Issue by igorkulman** [varoOP/shinkro#48]
I have shinkro running in docker, successfully authorized with MAL. It is not working and looking at the logs I think it cannot connect to Plex.

On the container startup I see

```
shinkro  | 2024-08-18 19:04:54 ERR error="unauthorized plex user" AuthorizedPlexUser=igorkulman module=server plexUserReceived=
shinkro  | 2024-08-18 19:06:22 FTL Caught signal terminated, Shutting Down
shinkro  | 2024-08-18 19:06:22 INF Starting shinkro
shinkro  | 2024-08-18 19:06:22 INF Version: v0.1.6
shinkro  | 2024-08-18 19:06:22 INF Commit: 
shinkro  | 2024-08-18 19:06:22 INF Build date: 2024-04-02T00:08:47.899Z
shinkro  | 2024-08-18 19:06:22 INF Base URL: /
shinkro  | 2024-08-18 19:06:22 INF Log-level: INFO
shinkro  | 2024-08-18 19:06:24 INF Starting HTTP server on 0.0.0.0:7011 module=server
```

I have put my the token into the config file

```
[shinkro]
Username = "shinkro"
Password = "shinkro"
Host = "0.0.0.0"
Port = 7011
ApiKey = "ABC"
#BaseUrl = "/shinkro"
#DiscordWebhookUrl = ""
LogLevel = "INFO"
LogMaxSize = 50
LogMaxBackups = 3

[plex]
PlexUsername = "igorkulman"
AnimeLibraries = ["Anime"]
Url = "http://192.168.1.187:32400"
Token = "XXX"
```

I am sure the value of the token is correct, I got it from the URL viewing XML details of an episode and I verified it printing `window.localStorage.myPlexAccessToken`  on the Plex website.

Later in logs I see

```
shinkro  | 2024-08-18 18:44:37 ERR failed to send update to myanimelist error="plex token not provided or invalid" action=animeUpdate module=server
```

But it guess it is the same problem.

**Comment by varoOP** [comment]
Hi, can you please set the LogLevel to "TRACE" in the config file, restart the application, reproduce the issue and then share the entire log with me? You can post it to something like https://privatebin.info/ and redact all sensitive information.

It's probably some sort of configuration issue, I'll know more with the TRACE logs

**Comment by igorkulman** [comment]
I set the log level to TRACE, restarted the container and the error went away. I even got an episode marked as seen in MAL.

I guess maybe it did not read the Plex token the first, but I restarted the container after setting the token.

Anyway, looks OK now, thanks.
